language: objective-c
osx_image: xcode8.1
cache:
- bundler
- cocoapods
before_install:
- bundle install
- bundle exec pod keys set MarvelApiKey $MARVEL_API_SECRET Marvel
- bundle exec pod keys set MarvelPrivateKey $MARVEL_API_PUBLIC Marvel
- pod repo update --silent
script:
- fastlane test
- bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: iQP72QQ4U3N8v2qLSiU1lcPv9enJAMFY9Bs/5MxI6D8gmOlVreEZloKVW4zS2pLcJITlttXiCLGCwi203DxbfnfXcdeEr04IsbWNDWv2NggtdSK1A/iQZDVIJGss0Qgvi6JW7+BVaPemCMhlndWxo4l0qkpj5jNvwS8bPWSPKJ1MB6AZlMQShktUlDYWujMcx3AfTgczLJbhiFrP8gpa6XCgFOu7lzlw6C+aqvRQgywUeLL9MKWge3OVBZnOMFtStB2ehUeKxvcp6HXOBIGaG8FVVef/NI+YXyLlX4wwLkuUsnR61lO/hEDMtL59ZE6SKOXDhXi00GyITT/E1k0sa/3caMgnQ5apHQxjN5y5vhc96CqEYnMyyAnwsgAktXpHqy5qU7TUJQ4EOfg67oFHFcXXqBbvFIh1AVM15e8oMZdEs/9GrDllm2KTY57FznO+XqqbmzLeFudaoVeWnXWsmy/M68RQZNp6cdRsBU+wVHu2k8uNwaIF91ouHm9sXJLcICFgvGZ/mg5r4nWza9Hu0gRk8FWLVNQtahjboS2OMAn+ZvyybjOungMvZoXU4ZJcXV4izAw6WIdUZgrU5GmzknWNwO1x8+AhJ7Lo/pkCsm22zV6HwB41sIo1CvJRfB8f8UvL7YPtU1DURNn7KIdju2C8jdi8Ae8onfkMknJQhNo=
  - secure: ZCih/6Pkg6kxc3V/GVfe29KYN1fL9EKVqdGz9vqMgfFyivDsz7a/WXXqoYBqyBXJ0Z9tT+13GZG1QidcZeLoxJ+RAvVvhtZhp4PBH4sa9dsy4laWZkA9hIRmgfoMR3M1Cuab+twmXBz/rPXkTWeOk9dBRlXe4BP5/QfzwrTz9NApezCV1vsGLGFVulQrClHE0USMA0eE6IiAACM7EsT4I4q063zJxQWAAsly9i/hbsL3J+1lUpqE4UcNamou/1Ri07VEFWYzM5Y87+dLB6pD1e96Cj7KjNfQVwBK9uw2K17i4oQt/kgwx8J2A4zdzCPF0kzu54Jmw6hUUrlv7sVscUfKKDPwtdqlQpS/ga7NgV43OzrhNrnnnjZQi7RRJAWvB33zsOjouEab9MVUS5vv6zi5uEUQj4eADgUlGbrhz9bw0Qdj2oX6UUWHnpyt5hS88cLqymZ5VLfvNwnrY3ZUzoGvFFu09KPrL1eUIgccanrpFqQHC0zqQZRiH1qKWH0dq8jgQNYE766mU1zypPge9wZW26dORatb8vat+lalt47wz38B2Wq818FgCN3PeeMyDr0xZoWInY0jTRB1eZzRhrVIX39MpyQ916bScCFr4Ex9biORiio0anUWUox1dyqSHvT/ZRpEdLf5YU2FhySh+9rEcAvluctXyHZvk5hYZUI=
